/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as airdropSol from "./Airdrop.sol";
export type { airdropSol };
import type * as tokens from "./tokens";
export type { tokens };
export type { NalndaBook } from "./NalndaBook";
export type { NalndaMarketplace } from "./NalndaMarketplace";
