/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockUsdtSol from "./mockUSDT.sol";
export type { mockUsdtSol };
export type { NalndaToken } from "./NalndaToken";
