/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { INalndaBook } from "./INalndaBook";
export type { INalndaMarketplace } from "./INalndaMarketplace";
