/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockUsdtSol from "./mockUSDT.sol";
export { NalndaToken__factory } from "./NalndaToken__factory";
