/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INalndaMarketplace,
  INalndaMarketplaceInterface,
} from "../../../contracts/interfaces/INalndaMarketplace";

const _abi = [
  {
    inputs: [],
    name: "NALNDA",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "transferAfterDays",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class INalndaMarketplace__factory {
  static readonly abi = _abi;
  static createInterface(): INalndaMarketplaceInterface {
    return new Interface(_abi) as INalndaMarketplaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): INalndaMarketplace {
    return new Contract(address, _abi, runner) as unknown as INalndaMarketplace;
  }
}
