/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { INalndaBook__factory } from "./INalndaBook__factory";
export { INalndaMarketplace__factory } from "./INalndaMarketplace__factory";
